### ISSUE TITLE
Get image from slider

### ISSUE THREAD

**Issue by brammahh** [larcus94/ImagePickerSheetController#61]
When the user takes a photo manually, the didFinishPickingWithOptions (or something really similar) method gets called so you can get the image from there. This also works when manually selecting from Photo Library. The problem I'm encountering it when using the slider to pick an image and click send, I can't get the image file. I can use controller.selectedImageAssets but it's a [phasset] file. 

How am I actually able to get a UIImage from the slider? I'm using the example code.

Thanks for your help, really like the layout of the custom picker!

**Comment by larcus94** [comment]
Hmm, what slider are you talking about exactly? The reason why it gives you back the images as `PHAsset` is so that it doesn't overload the memory, since `ImagePickerSheetController` can select multiple images.
Check out [this question](http://stackoverflow.com/questions/30812057/phasset-to-uiimage) on SO about retrieving the UIImage from it.

**Comment by brammahh** [comment]
Indeed, I came across that question too, and tried it with no luck. Xcode says PHAsset is expected and the controller.selectedImageAssets is of the type [PHAsset] which I wasn't able to convert to PHAsset..

**Comment by larcus94** [comment]
Oh, `[PHAsset]` is an array of `PHAsset` instances of course. So you'll need to access a specific element as follows: YOURARRAY[0]. This will return the first element of the array.

**Comment by brammahh** [comment]
Thanks man, sorry for that dumb mistake!

**Comment by larcus94** [comment]
No worries dude :)
